Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-09, with the labels that each got.

#1830 XML Site Map Bugs #1554
  admin/aioseop_module_class.php
  css/modules/aioseop_module.css
  inc/aioseop_functions.php
  inc/aiosp_common.php
  modules/aioseop_opengraph.php
  modules/aioseop_sitemap.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review, Completed Testing

#1448 Video XML Sitemap - Add column for video count to sitemap
  inc/sitemap-xsl.php
Labels: Completed Code Review, Completed Testing

#1876 Fixed option filtering
  all_in_one_seo_pack.php
  inc/compatability/compat-wpml.php
  modules/aioseop_sitemap.php
  readme.txt
Labels: Completed Code Review, Completed Testing

#1828 Fix/optimize sitemap generation
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#1907 XML Sitemap - add title and caption for images #1753
  modules/aioseop_sitemap.php
  tests/base/class-sitemap-test-base.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review, Completed Testing

#1904 Not possible to override OG data when page contains global Fusion Builder container #1804
  admin/aioseop_module_class.php
Labels: Completed Testing, Needs Code Review

#1898 Fix 1$ to %1$s
  aioseop_class.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#1900 updated profile and gravatar link
  admin/display/credits-content.php
Labels: Completed Code Review, Ready to merge

#1911 Remove our current Schema.org markup #413
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing
