Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-06, with the labels that each got.

#1710 pass array for #1709
  aioseop_class.php
Labels: Completed Testing, Needs Final Review

#1727 Issue 1694
  admin/aioseop_module_class.php
  aioseop_class.php
  js/modules/aioseop_module.js
Labels: Completed Code Review, Completed Testing, Ready to merge

#1737 Fixed tabindex for character counter box
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Testing
