Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-07, with the labels that each got.

#1746 Improved layout for Additional Pages section
  css/modules/aioseop_module.css
Labels: Completed Testing, Needs Code Review

#1764 Added Help link to docs
  modules/aioseop_robots.php
Labels: Completed Code Review

#1768 Issue 1762 - Fix JavaScript errors + jQuery corrections
  js/modules/aioseop_module.js
Labels: Completed Code Review, Completed Testing

#1782 Fix action issue for multisites
  all_in_one_seo_pack.php
Labels: Needs Code Review, Needs Testing

#1788 Fix import/delete static robot.txt file #1785
  admin/aioseop_module_class.php
  js/modules/aioseop_module.js
  modules/aioseop_robots.php
Labels: Completed Code Review, Needs Testing
