Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-10, with the labels that each got.

#1903 Add api filter hook to change sitemap filename #1703
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#1936 Fix WC Product Type issue with dropdown menu
  js/modules/aioseop_module.js
Labels: Completed Code Review, Completed Testing

#1942 Fix noindex not applied when SEO isn't active on post type
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#1944 Fix nofollow not applied when SEO isn't active on post type
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#1960 Remove SEMRush from bot blocklist
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Testing

#1959 Remove unneeded quotation mark in inline documentation
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#1886 Video XML Sitemap - Remove the Scan button
  aioseop_class.php
  all_in_one_seo_pack.php
  inc/aioseop_functions.php
  inc/commonstrings.php
Labels: Completed Code Review, Completed Testing

#1379 SEO meta is output when SEO for Custom Post Types is disabled
  aioseop_class.php
  tests/modules/general/test-meta.php
Labels: Completed Code Review, Completed Testing

#1350 Full size image for sitemap
  css/modules/aioseop_module.css
  inc/aiosp_common.php
  modules/aioseop_opengraph.php
  modules/aioseop_sitemap.php
  tests/base/class-aioseop-test-base.php
  tests/modules/sitemap/test-sitemap.php
  tests/resources/images/large-square.png
Labels: Completed Code Review, Completed Testing

#1432 XML Sitemap module - Add support for RSS/Atom updates
  modules/aioseop_sitemap.php
  tests/modules/sitemap/test-sitemap.php
  tests/resources/xsd/rss.xsd
Labels: Completed Code Review, Completed Testing

#1442 Pro - Use WooCommerce Product Image for OG Image
  css/modules/aioseop_module.css
  js/modules/aioseop_module.js
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing

#1935 Change to admin_enqueue_scripts
  admin/aioseop_module_class.php
  aioseop_class.php
  inc/aioseop_functions.php
Labels: Completed Code Review, Completed Testing

#1826 Robots.txt - Add an Edit Rule feature #1820
  js/modules/aioseop_module.js
  modules/aioseop_robots.php
  tests/modules/robots/test-robots-multisite.php
  tests/modules/robots/test-robots.php
Labels: Completed Code Review, Completed Testing

#1481 possible canonical URL issue
  aioseop_class.php
  tests/base/class-aioseop-test-base.php
  tests/modules/general/test-canonical-urls.php
Labels: Completed Code Review, Completed Testing

#1372 Special Characters Issue
  admin/aioseop_module_class.php
  css/modules/aioseop_module.css
  js/modules/aioseop_module.js
  modules/aioseop_opengraph.php
  tests/modules/opengraph/test-meta.php
Labels: Completed Code Review, Completed Testing

#1964 stop stripping brackets from description #1035
  aioseop_class.php
Labels: Completed Code Review, Ready to merge

#1319 Custom posts bbPress not outputting tags in source code
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#1962 Fix noindex & nofollow both required to operate
  aioseop_class.php
Labels: Completed Testing, Needs Code Review

#1472 Canonical urls on custom post type archive pages don't include the required URL variable
  aioseop_class.php
  js/modules/aioseop_module.js
  modules/aioseop_opengraph.php
  tests/base/class-sitemap-test-base.php
  tests/modules/general/test-canonical-urls.php
Labels: Completed Code Review, Completed Testing

#1430 Add hook to filter return of get_tax_args function
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#1968 Pagination not applied to custom canonical URLs #948
  aioseop_class.php
  tests/modules/general/test-canonical-urls.php
Labels: Completed Code Review, Completed Testing

#1966 Hide sitemap status toggle
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Testing, Ready to merge

#1958 Fix unordered list and remove unneeded bullet points
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#1461 Social Meta Module - OG Image not pulling in full size image
  admin/aioseop_module_class.php
  inc/aiosp_common.php
  modules/aioseop_opengraph.php
  modules/aioseop_sitemap.php
  tests/modules/opengraph/test-meta.php
  tests/modules/opengraph/test-opengraph.php
Labels: Completed Code Review, Completed Testing

#1981 remove sem rush from bad bod saved list
  inc/aioseop_updates_class.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#1983 Re-Fix WC Product Type issue with dropdown menu
  js/modules/aioseop_module.js
Labels: Completed Testing, Needs Code Review

#1982 Fix noindex & nofollow not printing
  aioseop_class.php
Labels: Completed Testing, Needs Code Review

#2001 Fix JS function name conflict with LearnDash
  js/modules/aioseop_module.js
Labels: Completed Code Review, Completed Testing, Priority | High

#2006 change custom post type language to content type
  aioseop_class.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#1992 Correct duplicate contributor name
  admin/display/credits-content.php
Labels: Completed Testing, Needs Code Review

#1998 Fix shortcodes affecting Auto Descriptions
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2016 Change Preview Snippet JS to a JS file
  aioseop_class.php
  js/count-chars.js
  js/modules/aioseop_module.js
Labels: Completed Code Review, Completed Testing, Ready to merge
