Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-02, with the labels that each got.

#1358 XML Sitemap - Blank sitemap pages with WPML
  modules/aioseop_sitemap.php
  tests/base/class-aioseop-test-base.php
  tests/base/class-sitemap-test-base.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Testing, Needs Code Review

#1549 XML Sitemap - Mandatory field causing settings not to save
  modules/aioseop_sitemap.php
Labels: Bug, Completed Testing, Needs Code Review

#1540 Fix Sitemap Notice from showing to non-admins #1345
  modules/aioseop_sitemap.php
Labels: Completed Testing, Needs Code Review

#1356 Fixed XML Parsing Error #1355
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing, Priority | High
