Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-12, with the labels that each got.

#2084 Cleanup Sitemap with WPCS
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2061 Update sitemap ping URLs for Google and Bing
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2058 No SEO output on homepage when there are no posts
  aioseop_class.php
Labels: Completed Code Review, Completed Testing, Needs Unit Tests

#2050 Remove option "SEO for Content Types"
  aioseop_class.php
  tests/modules/general/test-meta.php
Labels: Completed Testing, Needs Code Review, Needs Unit Tests

#2091 Fix Bad link to XML sitemap from error in merge conflict
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2098 Fix undefined variable aioseop_sitemap.php on line 476
  modules/aioseop_sitemap.php
Labels: Needs Testing

#2099 Fix undefined index in aioseop_class.php
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2101 Bug with video sitemap when added to XML Sitemap indexes
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing
