Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2018-03, with the labels that each got.

#1553 Bug in Custom Post Type Settings - Empty title format fields
  aioseop_class.php
Labels: Completed Testing, Needs Code Review

#1609 Improved inline help for Additional Pages URL field
  modules/aioseop_sitemap.php
Labels: Help | Docs, Needs Final Review

#1593 Possible duplicate function with moved PHPDoc block
  admin/aioseop_module_class.php
  inc/deprecated.php
Labels: Ready to merge

#1488 ACF macro is being output in titles and meta descriptions
  admin/aioseop_module_class.php
  aioseop_class.php
  tests/base/class-aioseop-test-base.php
  tests/modules/general/test-meta.php
Labels: Completed Testing, Needs Code Review

#1378 Correct tags order according to Sitemap protocol
  modules/aioseop_sitemap.php
  tests/base/class-sitemap-test-base.php
  tests/modules/sitemap/test-sitemap.php
  tests/resources/xsd/combined.xsd
  tests/resources/xsd/index.xsd
  tests/resources/xsd/sitemap-image.xsd
  tests/resources/xsd/sitemap.xsd
Labels: Completed Code Review, Completed Testing

#1286 handle scheme-less urls
  inc/aiosp_common.php
  modules/aioseop_sitemap.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review, Completed Testing

#1281 support external images
  modules/aioseop_sitemap.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review, Completed Testing

#1417 Make date format filterable
  aioseop_class.php
  inc/aioseop_functions.php
Labels: Completed Code Review, Completed Testing

#1435 Fix PHP Error with file_get_contents() & Sitemap not generating #1428
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#1595 Fix PHP Warning on Page Editor #1491
  aioseop_class.php
  tests/modules/general/test-All_in_One_SEO_Pack-aiospMrtGetUrl.php
Labels: Completed Code Review, Completed Testing

#1633 Fixed character counter for title & home title (#1581)
  js/modules/aioseop_module.js
Labels: Completed Testing, Needs Code Review
