Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-02, with the labels that each got.

#2199 Fix enqueue count-char.js when plugin folder name is altered
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2181 Use Schema.org Markup should remove all schema markup
  aioseop_class.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#2186 Styling issue with metabox on Edit Categories screen
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Testing

#2168 Fix PHP 7.3 warning
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#2183 Problem in XML sitemap caused by rsquo; character
  inc/aiosp_common.php
  tests/base/class-aioseop-test-base.php
Labels: Completed Testing, Ready to merge

#2211 Change Google Search Console verification documentation URL
  aioseop_class.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#2208 change location of logfile to content dir #555
  aioseop_class.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#2213 Rename Google Webmaster Tools to Google Search Console
  i18n/all-in-one-seo-pack.pot
  modules/aioseop_sitemap.php
Labels: In Development

#2202 Add Grunt
  .eslintrc
  .jshintrc
  Gruntfile.js
  admin/aioseop_module_class.php
  admin/display/credits-content.php
  admin/display/dashboard_widget.php
  admin/display/general-metaboxes.php
  admin/display/menu.php
  admin/meta_import.php
  aioseop_class.php
  inc/aioseop_functions.php
  inc/aioseop_updates_class.php
  inc/aiosp_common.php
  inc/sitemap-xsl.php
  js/count-chars.js
  js/count-chars.min.js
  js/modules/aioseop_module.js
  js/modules/aioseop_module.min.js
  js/modules/aioseop_opengraph.min.js
  js/quickedit_functions.js
  js/quickedit_functions.min.js
  js/welcome.js
  modules/aioseop_importer_exporter.php
  modules/aioseop_opengraph.php
  modules/aioseop_robots.php
  modules/aioseop_sitemap.php
  package.json
  phpcs.xml
  public/google-analytics.php
  tests/base/class-aioseop-test-base.php
  tests/base/class-sitemap-test-base.php
  tests/modules/general/test-All_in_One_SEO_Pack-aiospMrtGetUrl.php
  tests/modules/general/test-All_in_One_SEO_Pack_GetMainDescription.php
  tests/modules/general/test-canonical-urls.php
  tests/modules/general/test-meta.php
  tests/modules/opengraph/test-opengraph.php
  tests/modules/robots/test-robots-multisite.php
  tests/modules/robots/test-robots.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review

#2182 Add 'input' to allowed tags with 'html' escaping
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Testing

#2191 Fix href/URL output with <link> elements on paginated posts
  aioseop_class.php
Labels: Completed Testing, Priority | High

#2232 Social Meta module - Remove Blog from Object Type drop downs
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing, Ready to Merge

#1576 Filter for controlling which description to use for WooCommerce products
  aioseop_class.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing, Needs Final Review, Ready to Merge

#2161 Updating large sitemap locks out WP-API
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2107 Remove Exabot from bad bots blacklist
  admin/aioseop_module_class.php
  inc/aioseop_updates_class.php
Labels: Completed Code Review, Completed Testing, Ready to Merge
