Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-03, with the labels that each got.

#1855 Add Operative class for Admin Notices
  admin/class-aioseop-notices.php
  admin/display/notice-aioseop.php
  admin/display/notice-default.php
  admin/functions-notice.php
  all_in_one_seo_pack.php
  css/admin-notice.css
  js/admin-notice.js
  phpunit.xml.dist
  tests/base/class-aioseop-notices-testcase.php
  tests/classes/aioseop-notices/test-ajax.php
  tests/classes/aioseop-notices/test-delay-time.php
  tests/classes/aioseop-notices/test-enqueue-scripts.php
  tests/classes/aioseop-notices/test-init.php
  tests/classes/aioseop-notices/test-user.php
Labels: Completed Code Review, Completed Testing, Ready to Merge

#2236 Change Help Text Dropdown to Tooltips
  admin/aioseop_module_class.php
  admin/class-aioseop-helper.php
  aioseop_class.php
  css/modules/aioseop_module.css
  js/aioseop-helper.js
  js/aioseop-helper.min.js
  modules/aioseop_bad_robots.php
  modules/aioseop_file_editor.php
  modules/aioseop_importer_exporter.php
  modules/aioseop_opengraph.php
  modules/aioseop_performance.php
  modules/aioseop_robots.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2251 Minimum supported version is WP 4.6
  .travis.yml
Labels: Completed Code Review, Completed Testing

#2249 Integrate Grunt with Travis
  .travis.yml
  PULL_REQUEST_TEMPLATE.md
  bin/init-grunt.sh
  package.json
Labels: Completed Code Review, Completed Testing

#2270 Remove spaces before and after anchor text
  admin/display/general-metaboxes.php
  aioseop_class.php
  inc/commonstrings.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2288 Travis build fails for specific WP_VERSIONs because of PHPUnit version
  .travis.yml
Labels: Completed Code Review, Completed Grunt, Ready to Merge

#2289 Fix smaller width with label elements
  admin/aioseop_module_class.php
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2292 Change upgrade to Pro notice to AIOSEOP_Notices
  admin/functions-notice.php
  aioseop_class.php
  inc/aioseop_functions.php
  tests/classes/aioseop-notices/notices/test-pro-promo-woocommerce.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2299 Facebook SSL og:image only works if they have a non-SSL version cached
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2272 Non-existing /sitemap_XXX URLs navigate to empty sitemap instead of 404
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2260 Fixed whitespace in Settings & Edit Page
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2295 Add review plugin notice to AIOSEOP Notices class
  admin/functions-notice.php
  all_in_one_seo_pack.php
  tests/classes/aioseop-notices/notices/test-plugin-review.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2290 Use jQuery Tabs on Edit Post screen
  admin/aioseop_module_class.php
  css/modules/aioseop_module.css
  js/modules/aioseop_module.js
  js/modules/aioseop_module.min.js
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2315 remove check for jquery-ui #2274
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Grunt

#2297 OG descriptions and twitter descriptions are too big + twitter:title should be truncated
  modules/aioseop_opengraph.php
  tests/modules/opengraph/test-opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing
