Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-01, with the labels that each got.

#2130 Add Testcase for Descriptions
  tests/base/class-aioseop-test-base.php
  tests/modules/general/test-All_in_One_SEO_Pack_GetMainDescription.php
Labels: Ready to merge, Unit Test

#1873 Social Meta module - Incorrect default Object Type for taxonomies
  aioseop_class.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Needs Unit Tests

#2147 Rebased - XML Sitemap: Incorrect encoding of special characters
  inc/aiosp_common.php
  tests/base/class-aioseop-test-base.php
  tests/base/class-sitemap-test-base.php
Labels: Completed Code Review, Completed Testing

#2136 Sitemap Optimization (revised)
  inc/aiosp_common.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing, Ready to merge

#2159 Undefined index: aiosp_opengraph_options in aioseop_opengraph.php line 1101
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing
