Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-08, with the labels that each got.

#2752 Help text and documentation links for new Schema Settings
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Grunt, Completed Testing

#2760 Link welcome screen to release post
  admin/display/welcome-content.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2758 Fix homepage showing latest posts doesn't show up in sitemap
  modules/aioseop_sitemap.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2770 change boolvar to bool for < php 5.5
  aioseop_class.php
Labels: Completed Testing, Needs Code Review, Needs Grunt

#2786 Remove using post_content for generating schema description
  inc/schema/graphs/graph-webpage.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2787 Fix array_key_exists() expects array parameter notice in aioseop-class.php
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2777 Don't output default robots meta tag value
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2788 Fix broken Help link for Google Settings
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2798 Fix undefined index in (video) sitemap
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2800 Fix error with PHP 5.4 missing array_column()
  all_in_one_seo_pack.php
  inc/compatability/php-functions.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2817 Fix Travis configuration
  .travis.yml
  bin/install-phpunit.sh
  phpunit.xml.dist
Labels: Completed Code Review

#2816 Fix 404 issue for addl-sitemap file
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2815 Fix noindex for paginated content
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2833 Add support for Slack notifications
  .travis.yml
Labels: Completed Testing

#2846 Change order of Open Graph tags
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2839 Fix error undefined constant JSON_UNESCAPED_SLASHES
  inc/schema/graphs/graph-organization.php
  inc/schema/graphs/graph.php
  inc/schema/schema-builder.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2842 Update ogp.me link to HTTPS
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2844 Change section title Google Analytics
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge
