Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-09, with the labels that each got.

#2853 Improved display of date picker in Safari
  css/modules/aioseop_module-rtl.css
  css/modules/aioseop_module.css
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2856 Improve accessibility of tooltip help
  admin/aioseop_module_class.php
  aioseop_class.php
  modules/aioseop_importer_exporter.php
  modules/aioseop_performance.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2855 Fix version_updates not occuring on frontend
  all_in_one_seo_pack.php
  inc/aioseop_updates_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2878 Add closing tag to robots meta
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2841 Include Google Analytics on pages not checked in General Settings
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2871 Enable Schema by default
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2884 Add translator descriptions to credits-content.php
  admin/display/credits-content.php
Labels: Completed Code Review, Completed Grunt, Ready to Merge

#2883 Add translator descriptions for Schema.org settings
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt

#2873 Adds og:video:secure_url tag
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2890 Escape HTML before outputting the meta description
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2895 Add translator descriptions to aioseop_performance.php
  modules/aioseop_performance.php
Labels: Completed Code Review, Completed Grunt

#2894 Make bool ready for php upgrade
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2848 Improve Travis configuration
  .travis.yml
Labels: Completed Code Review

#2922 Only show Welcome Screen on major version updates
  admin/display/welcome.php
  inc/aioseop_functions.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2921 Fix conflict between Chromium v77.0.3865.75 and Gutenberg
  all_in_one_seo_pack.php
  css/modules/aioseop_module-rtl.min.css
  css/modules/aioseop_module.min.css
  inc/aioseop_updates_class.php
  inc/compatability/compat-gutenberg.php
  inc/compatability/compat-init.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2915 Add filter hook to disable schema.org markup
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2940 remove anon function for php 5.2 compat #2939
  inc/compatability/compat-gutenberg.php
Labels: Completed Code Review, Completed Grunt, Completed Testing
