Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-10, with the labels that each got.

#2907 Add PHPCompatibility sniffs to PHPCS & fix issues
  .gitignore
  .travis.yml
  Gruntfile.js
  admin/aioseop_module_class.php
  aioseop_class.php
  all_in_one_seo_pack.php
  bin/init-grunt.sh
  composer.json
  inc/aioseop_functions.php
  inc/aiosp_common.php
  inc/compatability/php-functions.php
  inc/compatibility/abstract/aiosep_compatible.php
  inc/compatibility/abstract/index.php
  inc/compatibility/compat-gutenberg.php
  inc/compatibility/compat-init.php
  inc/compatibility/compat-wpml.php
  inc/compatibility/index.php
  inc/compatibility/php-functions.php
  inc/schema/graphs/graph.php
  inc/schema/schema-builder.php
  js/aioseop-helper.js
  modules/aioseop_importer_exporter.php
  modules/aioseop_sitemap.php
  phpcs.xml
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2920 Change schema person's name & logo to add the option of manually ente…
  aioseop_class.php
  inc/schema/graphs/graph-organization.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2879 Add Schema to AMP plugin
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2966 Change bin path for phpcs
  Gruntfile.js
  bin/init-grunt.sh
Labels: Completed Code Review, Ready to Merge

#2961 Update help text for Sitemap Indexes setting
  admin/class-aioseop-helper.php
  inc/commonstrings.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2928 Remove version check for Gutenberg/Chrome compatibility fix and check if user agent is set
  inc/compatability/compat-init.php
  inc/compatability/gutenberg-chrome.php
Labels: Completed Grunt, Completed Testing

#2941 Refactor operations in All_in_One_SEO_Pack_Opengraph::add_meta()
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2947 Only output meta descriptions if autogenerate descriptions is enabled
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2964 Fix SEO for search results page
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2959 Added/updated help text for new Schema fields
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2955 Replace AJAX constant checks with wp_doing_ajax()
  all_in_one_seo_pack.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2986 3.2.10 to 3.3
  admin/class-aioseop-helper.php
  all_in_one_seo_pack.php
  inc/commonstrings.php
  inc/compatibility/compat-gutenberg.php
  inc/compatibility/compat-init.php
  inc/compatibility/gutenberg-chrome.php
  readme.txt
Labels: Completed Code Review, Completed Testing, Ready to Merge

#2984 bump requires WP 4.9
  readme.txt
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2989 Update Baidu verification documentation URL
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2993 Indent string and add translator description
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2987 Make strings untranslatable
  inc/schema/graphs/graph-webpage.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2978 Fixes CSS issues with WP v5.3
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2985 Add support for Google Tag Manager
  aioseop_class.php
  inc/compatibility/gutenberg-chrome.php
  public/google-analytics.php
Labels: Completed Code Review, Completed Grunt, Completed Testing
