Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-06, with the labels that each got.

#2550 Fix sitemap PHP errors with WP < 5.2
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2551 Fix sitemap not excluding posts properly with max_posts setting
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2562 Fix video sitemap PHP error with taxonomies
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2568 Fixed CSS applied to all textareas
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2563 (Possible) Fix cache with notices
  admin/class-aioseop-notices.php
  aioseop_class.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2570 Restrict .ui-sortable-handle span {} to aioseop options
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2571 Change review notice to display only on AIOSEOP screens
  admin/display/notices/review-plugin-notice.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2575 Fix Divi icon set
  css/aioseop-font-icons.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2577 Fix missing tabs when .hide is used by other plugins
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2581 Only show notices for PHP > 5.3.6
  admin/class-aioseop-notices.php
Labels: Completed Code Review, Completed Testing

#2587 Fix Travis failing PHP 5.5 & 5.4
  .travis.yml
  Gruntfile.js
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2586 Fix travis failing with notice test
  tests/base/class-aioseop-notices-testcase.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2590 restrict WC notice to our own screens
  admin/display/notices/wc-detected-notice.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2594 Disable review notice
  admin/class-aioseop-notices.php
  admin/display/notices/review-plugin-notice.php
  all_in_one_seo_pack.php
  inc/aioseop_updates_class.php
  tests/classes/aioseop-notices/notices/test-plugin-review.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2610 remove upgrade link from pro #2602
  admin/display/menu.php
Labels: Completed Code Review, Completed Grunt

#2617 Add and fix text domain for localizable strings
  admin/display/welcome-content.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2599 Fix aioseop_notice not loading database for users w/o 'aiosp_manage_seo' capabilities
  admin/class-aioseop-notices.php
  aioseop_class.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2618 Change JQuery CDN to Microsoft
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2627 Change XML Sitemap naming convention to fix index paginated filenames
  all_in_one_seo_pack.php
  inc/aioseop_updates_class.php
  modules/aioseop_sitemap.php
  readme.txt
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2626 Change grunt & coding standards
  admin/aioseop_module_class.php
  admin/aioseop_module_manager.php
  admin/class-aioseop-helper.php
  admin/class-aioseop-notices.php
  admin/display/credits-content.php
  admin/display/dashboard_widget.php
  admin/display/general-metaboxes.php
  admin/display/menu.php
  admin/display/notice-aioseop.php
  admin/display/notices/review-plugin-notice.php
  admin/display/welcome-content.php
  admin/display/welcome.php
  admin/meta_import.php
  aioseop-init.php
  aioseop_class.php
  all_in_one_seo_pack.php
  inc/aioseop_UTF8.php
  inc/aioseop_functions.php
  inc/aioseop_updates_class.php
  inc/aiosp_common.php
  inc/commonstrings.php
  inc/compatability/abstract/aiosep_compatible.php
  inc/compatability/compat-init.php
  inc/compatability/compat-wpml.php
  inc/sitemap-xsl.php
  inc/translations.php
  modules/aioseop_bad_robots.php
  modules/aioseop_feature_manager.php
  modules/aioseop_file_editor.php
  modules/aioseop_importer_exporter.php
  modules/aioseop_opengraph.php
  modules/aioseop_performance.php
  modules/aioseop_robots.php
  modules/aioseop_sitemap.php
  modules/aioseop_video_sitemap.php
  phpcs.xml
  public/front.php
  public/google-analytics.php
  public/opengraph.php
  tests/base/class-aioseop-notices-testcase.php
  tests/base/class-aioseop-test-base.php
  tests/base/class-sitemap-test-base.php
  tests/bootstrap.php
  tests/classes/aioseop-notices/notices/test-blog-visibility.php
  tests/classes/aioseop-notices/notices/test-pro-promo-woocommerce.php
  tests/classes/aioseop-notices/notices/test-sitemap-indexes.php
  tests/classes/aioseop-notices/test-delay-time.php
  tests/classes/aioseop-notices/test-enqueue-scripts.php
  tests/classes/aioseop-notices/test-init.php
  tests/classes/aioseop-notices/test-user.php
  tests/modules/general/test-All_in_One_SEO_Pack-aiospMrtGetUrl.php
  tests/modules/general/test-All_in_One_SEO_Pack_GetMainDescription.php
  tests/modules/general/test-canonical-urls.php
  tests/modules/general/test-meta.php
  tests/modules/general/test-rewrite-title.php
  tests/modules/general/test-shortcodes-in-description.php
  tests/modules/opengraph/test-opengraph.php
  tests/modules/robots/test-robots-multisite.php
  tests/modules/robots/test-robots.php
  tests/modules/sitemap/test-sitemap.php
Labels: Code Refactor, Completed Code Review, Completed Grunt, Completed Testing

#2655 Restrict jQuery UI styling to AIOSEOP
  admin/aioseop_module_class.php
  css/aioseop-jquery-ui.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2585 Updated sitemaps.org link to open in new tab with noopener and noreferrer
  inc/sitemap-xsl.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2661 Make plugin name constant dynamic
  all_in_one_seo_pack.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2659 Fix WooCommerce PHP memory limit warning
  all_in_one_seo_pack.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2663 Remove obsolete string
  inc/commonstrings.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2665 Remove double spacing from localized string
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2666 Fix casing for string
  inc/commonstrings.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2670 Add translator descriptions to aioseop_class.php (1)
  aioseop_class.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2668 Add translator descriptions to all_in_one_seo_pack.php
  all_in_one_seo_pack.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2667 Remove repeated placeholders
  admin/class-aioseop-helper.php
  admin/display/notices/review-plugin-notice.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2682 Updated inline help for Log important events
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Testing

#2681 Rename Admin Bar to Toolbar
  inc/commonstrings.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2679 Replaces links with buttons in Review notice
  admin/display/notices/review-plugin-notice.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2678 CSS fixes for alignment on Edit Post screen
  css/modules/aioseop_module-rtl.css
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2677 CSS fix for dashicon focus effect
  css/aioseop-font-icons.css
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2675 Improvements to help text for Robots module
  admin/class-aioseop-helper.php
  css/modules/aioseop_module.css
  modules/aioseop_robots.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2647 Fix for PHP notice when no posts present on homepage
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2676 Removes legacy code for Google Connect option
  admin/class-aioseop-helper.php
  aioseop_class.php
  inc/extlib/OAuth.php
  inc/extlib/index.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2656 Add %current_month% macro
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2689 Add cssmin and csslint to Grunt
  Gruntfile.js
  css/admin-notice.min.css
  css/aioseop-font-icons-rtl.min.css
  css/aioseop-font-icons.css
  css/aioseop-font-icons.min.css
  css/aiosp_admin.min.css
  css/modules/aioseop_module-rtl.min.css
  css/modules/aioseop_module.min.css
  css/welcome.min.css
  package.json
Labels: Completed Code Review, Completed Grunt, Completed Testing
