Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-04, with the labels that each got.

#2325 Sync with Pro & Add Filter for extended help text
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt

#2334 Video XML Sitemap - Remove taxonomy pages from video sitemap
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2347 Open Upgrade links as new tabs #773
  admin/display/general-metaboxes.php
  admin/display/menu.php
  all_in_one_seo_pack.php
  js/aioseop-menu.js
  js/aioseop-menu.min.js
  js/plugins-menu.js
  js/plugins-menu.min.js
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2350 Remove hardcoded path for Upgrade link in admin menu #2282
  admin/display/menu.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2358 Add Pro to sitemap source code
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2354 Remove redundant global $aioseop_plugin_name
  all_in_one_seo_pack.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2352 Use double quotes for pagination links
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2366 Change social meta home title field to text input
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2365 Use AIOSEOP_PLUGIN_NAME in sitemap instead of string
  inc/sitemap-xsl.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2362 Add Yandex and Baidu Webmaster Tools verification
  admin/class-aioseop-helper.php
  aioseop_class.php
  inc/compatability/compat-init.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2367 CSS improvement to text input fields
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing
