Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-11, with the labels that each got.

#2995 Force manual input for Schema.org Person when > 20 users
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#3025 Fix PHP warning
  inc/general/aioseop-robots-meta.php
Labels: Completed Code Review, Completed Testing

#3028 Change class member variable from static to instance
  inc/general/aioseop-robots-meta.php
Labels: Completed Code Review, Completed Testing

#3044 Add exclude rule to Grunt and fix remaining errors
  phpcs.xml
  tests/modules/general/test-rewrite-title.php
  tests/modules/general/test-shortcodes-in-description.php
Labels: Completed Code Review

#3007 Change define constants Name and Version with file data
  all_in_one_seo_pack.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#3048 Also pass $is_gutenberg along in Open Graph module
  js/admin/aioseop-count-chars.js
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#3051 Shorten post content before processing description
  js/admin/aioseop-preview-snippet.js
Labels: Completed Code Review, Completed Testing

#3058 Remove conditional checks for advanced GA settings in free
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#3059 Add Preview Snippet & Character Counter support for text tab of Classic Editor
  .jshintrc
  aioseop_class.php
  js/admin/aioseop-admin-functions.js
  js/admin/aioseop-count-chars-old.min.js
  js/admin/aioseop-count-chars.js
  js/admin/aioseop-count-chars.min.js
  js/admin/aioseop-preview-snippet.js
  js/admin/aioseop-preview-snippet.min.js
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing

#3064 Improve regex pattern to remove new lines
  js/admin/aioseop-preview-snippet.js
Labels: Completed Code Review, Completed Testing

#3045 Refactor main plugin file into a core class
  aioseop-init.php
  all_in_one_seo_pack.php
  class-aioseop-core.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#3063 Adds an additional shortcode for NextGen Gallery
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge
