Repository awesomemotive/all-in-one-seo-pack, pull requests merged in 2019-05, with the labels that each got.

#2369 Add separate mailing list for Pro users
  admin/display/general-metaboxes.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2317 Change Sitemap to exclude NOINDEX post types & posts
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2360 Add %site_title% and %site_description% macros
  admin/class-aioseop-helper.php
  aioseop_class.php
  inc/aioseop_functions.php
  tests/modules/general/test-meta.php
  tests/modules/general/test-rewrite-title.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Has Unit Test

#2388 Add %current_year% macro
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2397 Remove spaces from translatable strings
  admin/display/general-metaboxes.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2391 Make remaining strings translatable
  admin/display/dashboard_widget.php
  admin/display/general-metaboxes.php
  aioseop_class.php
  inc/sitemap-xsl.php
  modules/aioseop_performance.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2390 remove Google+ (and two filter hooks)
  admin/class-aioseop-helper.php
  aioseop_class.php
  inc/aioseop_functions.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2400 Change "blog" to "site"
  admin/class-aioseop-helper.php
  aioseop_class.php
  all_in_one_seo_pack.php
  modules/aioseop_feature_manager.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2379 Fix exclude terms from custom taxonomies
  admin/aioseop_module_class.php
  admin/class-aioseop-helper.php
  css/modules/aioseop_module.css
  inc/aioseop_updates_class.php
  js/modules/aioseop_sitemap.js
  js/modules/aioseop_sitemap.min.js
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2410 Remove support for WP < 4.7
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2407 Update plugin icon to modern gear logo
  aioseop_class.php
  css/aiosp_admin.css
  images/shield-sprite-16.png
  images/shield-sprite-32.png
  images/shield32.png
  images/shield32fade.png
  images/shield64.png
  inc/aioseop_functions.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2408 Add character counter fields to OG Home Title & Description
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2414 Default to sitemap indexes and 1000 posts per sitemap file
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2421 make social user profile fields more obviously from aioseop
  css/aiosp_admin.css
  inc/aioseop_functions.php
Labels: Completed Code Review, Completed Testing, Ready to Merge

#2418 Remove Enable Custom Canonical URLs option and checks
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2417 remove sitemap compression #534
  admin/class-aioseop-helper.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Testing

#2428 Make contextual help more clear for Exclude Pages setting
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Testing

#2426 Change 'Media' to 'Media / Attachments'
  admin/aioseop_module_class.php
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2431 Make WC upgrade button orange
  admin/functions-notice.php
  css/admin-notice.css
  css/welcome.css
Labels: Completed Code Review, Completed Testing

#2427 Fix undefined $tag in aioseop_opengraph.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing

#2434 Change link for schema.org to HTTPS
  aioseop_class.php
  modules/aioseop_opengraph.php
Labels: Completed Code Review, Completed Testing

#2433 Remove Preferred Site Name setting
  admin/class-aioseop-helper.php
  aioseop_class.php
Labels: Completed Code Review, Completed Testing

#2409 Change recommended OG description length
  modules/aioseop_opengraph.php
  tests/modules/opengraph/test-opengraph.php
Labels: Completed Code Review, Completed Testing

#2438 Improve look of tooltips
  css/aiosp_admin.css
Labels: Completed Code Review, Completed Testing

#2441 Add custom CSS to tooltips
  css/aiosp_admin.css
  js/aioseop-helper.js
Labels: Completed Code Review, Completed Testing

#2453 remove space in translated string #2452
  inc/commonstrings.php
Labels: Completed Code Review, Completed Testing

#2451 match translation request language
  admin/display/general-metaboxes.php
  inc/translations.php
Labels: Completed Code Review, Completed Testing

#2443 Improve help text for new tooltips
  admin/class-aioseop-helper.php
  css/aiosp_admin.css
  js/aioseop-helper.min.js
Labels: Completed Code Review, Completed Testing

#2445 Add filter hook for adding custom title formatting
  aioseop_class.php
Labels: Completed Grunt, Completed Testing

#2459 Add aioseop_pre_tax_types_setting filter hook
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2463 Add missing index files to each directory
  admin/display/notices/index.php
  css/index.php
  css/modules/index.php
  images/index.php
  inc/compatability/abstract/index.php
  inc/compatability/index.php
  inc/extlib/index.php
  js/index.php
  js/modules/index.php
  modules/images/index.php
  public/js/vendor/index.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2473 Updated inline help for Additional Pages
  admin/class-aioseop-helper.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2470 Fix error invalid arg supplied for foreach in sitemap class
  modules/aioseop_sitemap.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2486 rename clean_url to aioseop_clean_url
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2483 Fix empty items for excl terms to select in sitemap settings
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2496 Changed Support Metabox Icons to Font-Icons
  admin/aioseop_module_class.php
  admin/display/general-metaboxes.php
  all_in_one_seo_pack.php
  css/aioseop-font-icons.css
  css/font-icons/aioseop.eot
  css/font-icons/aioseop.svg
  css/font-icons/aioseop.ttf
  css/font-icons/aioseop.woff
  css/modules/aioseop_module.css
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2490 remove extra filter hook arguments
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2491 extract newline out of translatable string
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2494 Change AJAX accept & delete to Font-Icons
  css/aioseop-font-icons.css
  inc/aioseop_functions.php
  js/quickedit_functions.js
Labels: Completed Code Review, Completed Grunt, Completed Testing, Merge Conflict, Ready to Merge

#2495 Change cog_edit to Font-Icon
  css/aioseop-font-icons.css
  inc/aioseop_functions.php
Labels: Completed Grunt, Completed Testing, Ready to Merge

#2493 Move Tip Icon to font-icon.css
  css/aioseop-font-icons.css
  css/modules/aioseop_module.css
Labels: Completed Code Review, Completed Grunt, Completed Testing, Merge Conflict, Ready to Merge

#2492 Move About Metabox DashIcons
  css/aioseop-font-icons.css
  css/aiosp_admin.css
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2508 Fix syntax error
  admin/aioseop_module_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Needs Code Review

#2511 Fix unused variable
  aioseop_class.php
Labels: Completed Grunt, Completed Testing, Needs Code Review

#2500 Update help text for Excluded Terms setting
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2509 fix missing character and switch to double quotes
  admin/class-aioseop-notices.php
Labels: Completed Code Review, Completed Grunt, Completed Testing, Ready to Merge

#2501 Refactor help text strings for XML Sitemap menu
  admin/class-aioseop-helper.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2485 Make "All in One SEO Pack" string untranslatable
  admin/class-aioseop-helper.php
  admin/display/credits-content.php
  admin/display/general-metaboxes.php
  admin/display/notices/blog-visibility.php
  admin/display/welcome-content.php
  admin/display/welcome.php
  admin/functions-notice.php
  admin/meta_import.php
  aioseop_class.php
  inc/aioseop_functions.php
  inc/commonstrings.php
  modules/aioseop_feature_manager.php
  modules/aioseop_importer_exporter.php
  modules/aioseop_performance.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2520 replace sitemap url in robotstxt option with filter hook
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2484 Fix meta box help icon alignment
  css/modules/aioseop_module-rtl.css
  css/modules/aioseop_module.css
Labels: Completed Grunt, Completed Testing

#2518 Import SEO data from Rank Math
  admin/meta_import.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2517 Refactor AIOSEOP_Notices notice operations to include hook
  admin/class-aioseop-notices.php
  admin/display/notice-aioseop.php
  admin/display/notice-default.php
  admin/display/notices/blog-visibility-notice.php
  admin/display/notices/review-plugin-notice.php
  admin/display/notices/sitemap-indexes-notice.php
  admin/display/notices/wc-detected-notice.php
  admin/functions-notice.php
  aioseop_class.php
  all_in_one_seo_pack.php
  modules/aioseop_sitemap.php
  tests/base/class-aioseop-notices-testcase.php
  tests/classes/aioseop-notices/notices/test-blog-visibility.php
  tests/classes/aioseop-notices/notices/test-plugin-review.php
  tests/classes/aioseop-notices/notices/test-pro-promo-woocommerce.php
  tests/classes/aioseop-notices/notices/test-sitemap-indexes.php
  tests/classes/aioseop-notices/test-ajax.php
  tests/classes/aioseop-notices/test-delay-time.php
  tests/classes/aioseop-notices/test-enqueue-scripts.php
  tests/classes/aioseop-notices/test-init.php
  tests/classes/aioseop-notices/test-user.php
Labels: Completed Testing, Has Unit Test

#2522 remove rewrite_titles option #69
  admin/class-aioseop-helper.php
  aioseop_class.php
  modules/aioseop_performance.php
Labels: Needs Grunt

#2531 Fix typo in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Needs Code Review

#2530 Fix Grunt issues in aioseop_class.php
  aioseop_class.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2532 update pro strings in commonstrings.php
  inc/commonstrings.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2512 Improve look of meta box and menus
  admin/aioseop_module_class.php
  admin/display/general-metaboxes.php
  admin/meta_import.php
  aioseop_class.php
  all_in_one_seo_pack.php
  css/aioseop-font-icons-rtl.css
  css/modules/aioseop_module-rtl.css
  css/modules/aioseop_module.css
  js/quickedit_functions.min.js
  modules/aioseop_importer_exporter.php
  modules/aioseop_robots.php
  modules/aioseop_sitemap.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2488 Don't run conflicting shortcodes in autogenerated descriptions
  aioseop_class.php
  inc/aioseop_functions.php
  modules/aioseop_opengraph.php
  modules/aioseop_sitemap.php
  tests/modules/general/test-shortcodes-in-description.php
  tests/modules/sitemap/test-sitemap.php
Labels: Completed Grunt, Completed Testing

#2543 Make Button Orange Again
  admin/display/notices/wc-detected-notice.php
Labels: Completed Code Review, Completed Grunt, Completed Testing

#2541 Fix sitemap index 1000+ posts notice check
  admin/class-aioseop-notices.php
  modules/aioseop_sitemap.php
Labels: Completed Grunt, Completed Testing
